/*=====================================================================
  TURISMOUQ - ENTREGA 1
  Script 01: DDL completo (tablas + PK + FK + CHECK + NOT NULL + UNIQUE)
=====================================================================*/

SET DEFINE OFF;

/*---------------------------------------------------------------------
  0. Limpieza para permitir repetir el ejercicio en desarrollo.
---------------------------------------------------------------------*/
BEGIN
  FOR t IN (
    SELECT table_name
    FROM user_tables
    WHERE table_name IN (
      'RESERVA_SERVICIO','RESERVA_HABITACION','PAGO','RESENA','RESERVA',
      'TARIFA','SERVICIO','HABITACION','ALOJAMIENTO','USUARIO_SISTEMA',
      'TEMPORADA','CLIENTE','TIPO_ALOJAMIENTO','MUNICIPIO'
    )
    ORDER BY CASE table_name
      WHEN 'RESERVA_SERVICIO' THEN 1
      WHEN 'RESERVA_HABITACION' THEN 2
      WHEN 'PAGO' THEN 3
      WHEN 'RESENA' THEN 4
      WHEN 'RESERVA' THEN 5
      WHEN 'TARIFA' THEN 6
      WHEN 'SERVICIO' THEN 7
      WHEN 'HABITACION' THEN 8
      WHEN 'ALOJAMIENTO' THEN 9
      WHEN 'USUARIO_SISTEMA' THEN 10
      WHEN 'TEMPORADA' THEN 11
      WHEN 'CLIENTE' THEN 12
      WHEN 'TIPO_ALOJAMIENTO' THEN 13
      WHEN 'MUNICIPIO' THEN 14
      ELSE 99
    END
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

/*---------------------------------------------------------------------
  1. Catálogos geográficos y de clasificación.
---------------------------------------------------------------------*/
CREATE TABLE municipio (
  id_municipio NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre       VARCHAR2(60) NOT NULL,
  departamento VARCHAR2(60) DEFAULT 'Quindío' NOT NULL,
  CONSTRAINT pk_municipio PRIMARY KEY (id_municipio),
  CONSTRAINT uq_municipio_nombre UNIQUE (nombre)
);

CREATE TABLE tipo_alojamiento (
  id_tipo_alojamiento NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre              VARCHAR2(40) NOT NULL,
  descripcion         VARCHAR2(250),
  CONSTRAINT pk_tipo_alojamiento PRIMARY KEY (id_tipo_alojamiento),
  CONSTRAINT uq_tipo_alojamiento_nombre UNIQUE (nombre)
);

/*---------------------------------------------------------------------
  2. Oferta de alojamientos, habitaciones, temporadas y tarifas.
---------------------------------------------------------------------*/
CREATE TABLE alojamiento (
  id_alojamiento     NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_municipio       NUMBER NOT NULL,
  id_tipo_alojamiento NUMBER NOT NULL,
  nombre_comercial   VARCHAR2(120) NOT NULL,
  direccion          VARCHAR2(180) NOT NULL,
  estrellas          NUMBER(1) NOT NULL,
  telefono           VARCHAR2(20) NOT NULL,
  correo             VARCHAR2(120) NOT NULL,
  CONSTRAINT pk_alojamiento PRIMARY KEY (id_alojamiento),
  CONSTRAINT uq_alojamiento_correo UNIQUE (correo),
  CONSTRAINT ck_alojamiento_estrellas CHECK (estrellas BETWEEN 1 AND 5),
  CONSTRAINT fk_alojamiento_municipio FOREIGN KEY (id_municipio)
    REFERENCES municipio(id_municipio),
  CONSTRAINT fk_alojamiento_tipo FOREIGN KEY (id_tipo_alojamiento)
    REFERENCES tipo_alojamiento(id_tipo_alojamiento)
);

CREATE TABLE habitacion (
  id_habitacion       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_alojamiento      NUMBER NOT NULL,
  numero_habitacion   VARCHAR2(10) NOT NULL,
  capacidad_maxima    NUMBER(2) NOT NULL,
  tipo_habitacion     VARCHAR2(20) NOT NULL,
  descripcion         VARCHAR2(500),
  CONSTRAINT pk_habitacion PRIMARY KEY (id_habitacion),
  CONSTRAINT uq_habitacion_numero_alojamiento UNIQUE (id_alojamiento, numero_habitacion),
  CONSTRAINT ck_habitacion_capacidad CHECK (capacidad_maxima BETWEEN 1 AND 12),
  CONSTRAINT ck_habitacion_tipo CHECK (tipo_habitacion IN ('SENCILLA','DOBLE','SUITE','CABAÑA')),
  CONSTRAINT fk_habitacion_alojamiento FOREIGN KEY (id_alojamiento)
    REFERENCES alojamiento(id_alojamiento)
);

CREATE TABLE temporada (
  id_temporada       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre             VARCHAR2(80) NOT NULL,
  anio               NUMBER(4) NOT NULL,
  tipo_temporada     VARCHAR2(10) NOT NULL,
  fecha_inicio       DATE NOT NULL,
  fecha_fin          DATE NOT NULL,
  CONSTRAINT pk_temporada PRIMARY KEY (id_temporada),
  CONSTRAINT uq_temporada_rango UNIQUE (fecha_inicio, fecha_fin),
  CONSTRAINT ck_temporada_tipo CHECK (tipo_temporada IN ('ALTA','MEDIA','BAJA')),
  CONSTRAINT ck_temporada_fechas CHECK (fecha_fin >= fecha_inicio),
  CONSTRAINT ck_temporada_anio CHECK (anio BETWEEN 2023 AND 2100)
);

CREATE TABLE tarifa (
  id_tarifa      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_habitacion  NUMBER NOT NULL,
  id_temporada   NUMBER NOT NULL,
  precio_noche   NUMBER(12,2) NOT NULL,
  CONSTRAINT pk_tarifa PRIMARY KEY (id_tarifa),
  CONSTRAINT uq_tarifa_habitacion_temporada UNIQUE (id_habitacion, id_temporada),
  CONSTRAINT ck_tarifa_precio CHECK (precio_noche > 0),
  CONSTRAINT fk_tarifa_habitacion FOREIGN KEY (id_habitacion)
    REFERENCES habitacion(id_habitacion),
  CONSTRAINT fk_tarifa_temporada FOREIGN KEY (id_temporada)
    REFERENCES temporada(id_temporada)
);

CREATE TABLE servicio (
  id_servicio        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_alojamiento     NUMBER NOT NULL,
  nombre             VARCHAR2(100) NOT NULL,
  descripcion        VARCHAR2(300),
  precio             NUMBER(12,2) NOT NULL,
  activo             CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_servicio PRIMARY KEY (id_servicio),
  CONSTRAINT uq_servicio_nombre_alojamiento UNIQUE (id_alojamiento, nombre),
  CONSTRAINT ck_servicio_precio CHECK (precio > 0),
  CONSTRAINT ck_servicio_activo CHECK (activo IN ('S','N')),
  CONSTRAINT fk_servicio_alojamiento FOREIGN KEY (id_alojamiento)
    REFERENCES alojamiento(id_alojamiento)
);

/*---------------------------------------------------------------------
  3. Clientes, reservas y detalle de habitaciones.
---------------------------------------------------------------------*/
CREATE TABLE cliente (
  id_cliente          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre_completo     VARCHAR2(120) NOT NULL,
  documento_identidad VARCHAR2(30) NOT NULL,
  correo              VARCHAR2(120) NOT NULL,
  telefono            VARCHAR2(20) NOT NULL,
  ciudad_origen       VARCHAR2(80) NOT NULL,
  CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
  CONSTRAINT uq_cliente_documento UNIQUE (documento_identidad),
  CONSTRAINT uq_cliente_correo UNIQUE (correo)
);

CREATE TABLE reserva (
  id_reserva        NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_cliente        NUMBER NOT NULL,
  fecha_check_in    DATE NOT NULL,
  fecha_check_out   DATE NOT NULL,
  estado            VARCHAR2(15) NOT NULL,
  fecha_creacion    DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_reserva PRIMARY KEY (id_reserva),
  CONSTRAINT ck_reserva_estado CHECK (estado IN ('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA')),
  CONSTRAINT ck_reserva_fechas CHECK (fecha_check_out > fecha_check_in),
  CONSTRAINT fk_reserva_cliente FOREIGN KEY (id_cliente)
    REFERENCES cliente(id_cliente)
);

CREATE TABLE reserva_habitacion (
  id_reserva_habitacion NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_reserva            NUMBER NOT NULL,
  id_habitacion         NUMBER NOT NULL,
  fecha_check_in        DATE NOT NULL,
  fecha_check_out       DATE NOT NULL,
  numero_huespedes      NUMBER(2) NOT NULL,
  CONSTRAINT pk_reserva_habitacion PRIMARY KEY (id_reserva_habitacion),
  CONSTRAINT ck_rh_fechas CHECK (fecha_check_out > fecha_check_in),
  CONSTRAINT ck_rh_huespedes CHECK (numero_huespedes > 0),
  CONSTRAINT uq_rh_reserva_habitacion_fecha UNIQUE
    (id_reserva, id_habitacion, fecha_check_in, fecha_check_out),
  CONSTRAINT fk_rh_reserva FOREIGN KEY (id_reserva)
    REFERENCES reserva(id_reserva),
  CONSTRAINT fk_rh_habitacion FOREIGN KEY (id_habitacion)
    REFERENCES habitacion(id_habitacion)
);

CREATE TABLE pago (
  id_pago       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_reserva    NUMBER NOT NULL,
  fecha_pago    DATE DEFAULT SYSDATE NOT NULL,
  monto         NUMBER(12,2) NOT NULL,
  metodo        VARCHAR2(25) NOT NULL,
  estado        VARCHAR2(15) NOT NULL,
  CONSTRAINT pk_pago PRIMARY KEY (id_pago),
  CONSTRAINT ck_pago_monto CHECK (monto > 0),
  CONSTRAINT ck_pago_metodo CHECK (metodo IN ('TARJETA_CREDITO','TARJETA_DEBITO','PSE','TRANSFERENCIA','EFECTIVO')),
  CONSTRAINT ck_pago_estado CHECK (estado IN ('EXITOSO','FALLIDO','PENDIENTE','REEMBOLSADO')),
  CONSTRAINT fk_pago_reserva FOREIGN KEY (id_reserva)
    REFERENCES reserva(id_reserva)
);

/*---------------------------------------------------------------------
  4. Servicios contratados por reserva.
  precio_unitario conserva el precio vigente al momento de contratar.
---------------------------------------------------------------------*/
CREATE TABLE reserva_servicio (
  id_reserva_servicio NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_reserva          NUMBER NOT NULL,
  id_servicio         NUMBER NOT NULL,
  fecha_servicio      DATE NOT NULL,
  cantidad            NUMBER(4) NOT NULL,
  precio_unitario     NUMBER(12,2) NOT NULL,
  CONSTRAINT pk_reserva_servicio PRIMARY KEY (id_reserva_servicio),
  CONSTRAINT ck_rs_cantidad CHECK (cantidad > 0),
  CONSTRAINT ck_rs_precio CHECK (precio_unitario > 0),
  CONSTRAINT uq_rs_linea UNIQUE (id_reserva, id_servicio, fecha_servicio),
  CONSTRAINT fk_rs_reserva FOREIGN KEY (id_reserva)
    REFERENCES reserva(id_reserva),
  CONSTRAINT fk_rs_servicio FOREIGN KEY (id_servicio)
    REFERENCES servicio(id_servicio)
);

/*---------------------------------------------------------------------
  5. Reseñas y usuarios internos.
---------------------------------------------------------------------*/
CREATE TABLE resena (
  id_resena      NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_cliente     NUMBER NOT NULL,
  id_alojamiento NUMBER NOT NULL,
  id_reserva     NUMBER NOT NULL,
  calificacion   NUMBER(1) NOT NULL,
  comentario     VARCHAR2(800),
  fecha_resena   DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_resena PRIMARY KEY (id_resena),
  CONSTRAINT uq_resena_cliente_alojamiento UNIQUE (id_cliente, id_alojamiento),
  CONSTRAINT ck_resena_calificacion CHECK (calificacion BETWEEN 1 AND 5),
  CONSTRAINT fk_resena_cliente FOREIGN KEY (id_cliente)
    REFERENCES cliente(id_cliente),
  CONSTRAINT fk_resena_alojamiento FOREIGN KEY (id_alojamiento)
    REFERENCES alojamiento(id_alojamiento),
  CONSTRAINT fk_resena_reserva FOREIGN KEY (id_reserva)
    REFERENCES reserva(id_reserva)
);

CREATE TABLE usuario_sistema (
  id_usuario       NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre_usuario   VARCHAR2(50) NOT NULL,
  rol              VARCHAR2(20) NOT NULL,
  id_alojamiento   NUMBER,
  activo           CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_usuario_sistema PRIMARY KEY (id_usuario),
  CONSTRAINT uq_usuario_sistema_nombre UNIQUE (nombre_usuario),
  CONSTRAINT ck_usuario_rol CHECK (rol IN ('ADMINISTRADOR','ENCARGADO')),
  CONSTRAINT ck_usuario_activo CHECK (activo IN ('S','N')),
  CONSTRAINT ck_usuario_alojamiento CHECK (
    (rol = 'ADMINISTRADOR' AND id_alojamiento IS NULL)
    OR
    (rol = 'ENCARGADO' AND id_alojamiento IS NOT NULL)
  ),
  CONSTRAINT fk_usuario_alojamiento FOREIGN KEY (id_alojamiento)
    REFERENCES alojamiento(id_alojamiento)
);

/*---------------------------------------------------------------------
  6. Comentarios de documentación del modelo.
---------------------------------------------------------------------*/
COMMENT ON TABLE municipio IS 'Municipios del departamento del Quindío donde existe oferta turística.';
COMMENT ON TABLE tipo_alojamiento IS 'Catálogo de tipos de alojamiento ofrecidos por TurismoUQ.';
COMMENT ON TABLE alojamiento IS 'Oferta turística; cada alojamiento pertenece a un municipio y a un tipo.';
COMMENT ON TABLE habitacion IS 'Habitaciones disponibles por alojamiento; el número es único dentro de cada alojamiento.';
COMMENT ON TABLE temporada IS 'Periodos tarifarios; se definen por año y por rango de fechas.';
COMMENT ON TABLE tarifa IS 'Precio por noche de una habitación para una temporada específica.';
COMMENT ON TABLE cliente IS 'Personas que realizan reservas en TurismoUQ.';
COMMENT ON TABLE reserva IS 'Cabecera de una reserva; una reserva puede contener varias habitaciones.';
COMMENT ON TABLE reserva_habitacion IS 'Detalle de habitaciones de una reserva, con fechas propias por línea.';
COMMENT ON TABLE pago IS 'Abonos y pagos asociados a una reserva.';
COMMENT ON TABLE servicio IS 'Servicios complementarios ofrecidos por un alojamiento.';
COMMENT ON TABLE reserva_servicio IS 'Servicios contratados por una reserva, con cantidad, fecha y precio congelado.';
COMMENT ON TABLE resena IS 'Reseñas de clientes sobre alojamientos después de una estadía completada.';
COMMENT ON TABLE usuario_sistema IS 'Usuarios internos de la plataforma y su alcance sobre los alojamientos.';

COMMENT ON COLUMN temporada.fecha_fin IS 'Límite inclusivo del periodo tarifario.';
COMMENT ON COLUMN reserva_habitacion.fecha_check_out IS 'Fecha sin noche incluida; la noche se calcula desde check-in hasta el día anterior al check-out.';
COMMENT ON COLUMN reserva_servicio.precio_unitario IS 'Copia del precio del servicio al momento de contratarlo.';
COMMENT ON COLUMN usuario_sistema.id_alojamiento IS 'Nulo para administradores y obligatorio para encargados.';

COMMIT;

PROMPT ================================================================
PROMPT TurismoUQ - DDL creado correctamente.
PROMPT ================================================================
